### ISSUE TITLE
三元运算符省略表达式1会报编译错误

### ISSUE THREAD

**Issue by moshuqi** [Kejiasir/YYRSACrypto#1]
如类似这样的代码
!decryptError ?: ({ NSLog(@"private decrypt error: %@",decryptError); });

用pod install安装一直装不上不知道为什么。

最后感谢楼主分享的源码帮忙解决了加密问题。：）

**Comment by Kejiasir** [comment]
编译报错跟pod安装不上是两个事是吗？能麻烦贴个错误信息吗？三元表达式那里只是判断有错误时并且是debug的时候才输出，如果编译报错估计是那个nslog的宏

moshuqi <notifications@github.com>于2018年6月6日 周三12:04写道：

**Comment by moshuqi** [comment]
!block ?: block((MIHKeyPair *)[NSKeyedUnarchiver unarchiveObjectWithFile:filePath]);

比如说这行，编译的时候提示错误，Right operand to ? is void, but left operand is of type 'int'

pod安装不上我只是顺便提一下

**Comment by Kejiasir** [comment]
🤔你的是Xcode几？我这边连警告都没有一个

moshuqi <notifications@github.com>于2018年6月6日 周三12:42写道：

**Comment by moshuqi** [comment]
9.4，猜可能和项目配置有关，我直接下你的项目是能正常跑起来的，单独拷到我的项目之后就有问题了
